#!/usr/bin/env bash

#pgrep -x sxhkd > /dev/null || 

#pkill -f testwallpaper
#pkill -f sleep

sxhkd -c /home/phil/.config/bspwm/sxhkdrc &
#~/.config/bspwm/cursor.sh &

#killall testwallpaper
#killall lxpolkit
#killall xcompmgr

#~/.config/bspwm/testwallpaper &

setxkbmap gb &
lxpolkit &
xcompmgr -c &
#volumeicon &
nm-applet &
blueman-applet &

$HOME/.config/polybar-bspwm/launch.sh &

################################Together####
####~/.config/bspwm/sta &
#~/.local/bin/succade &
############################################

######PATH not set yet############
#~/.config/bspwm/launch.sh NOT USED





bspc monitor -d I II III IV V VI

bspc config border_width         2
bspc config window_gap          15

bsp config presel_feedback_color "#ffffff"

bspc config normal_border_color "#454849"



bspc config focused_border_color "#3399ff"


bspc config top_padding 38

bspc config focus_follows_pointer true

#####bspc config initial_polarity second_child
#####bspc config automatic_scheme longest_side

##bspc config automatic_scheme spiral
##bspc config automatic_scheme longest_side
##bspc config initial_polarity second_child

#bspc config history_aware_focus	false
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config center_pseudo_tiled true
 
# Automatic Splitting Settings
bspc config automatic_scheme	spiral
bspc config initial_polarity	first_child





bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Brave desktop='^2'
bspc rule -a Xfce4-appfinder state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
#bspc rule -a firefox desktop=^2
#bspc rule -a Geany desktop=^3
bspc rule -a Xfce4-terminal state=floating
