#!/bin/bash

MEMUSED=$(free -h | awk '(NR==2) {print $3}')
MEMTOT=$(free -h | awk '(NR==2) {print $2}')


icon=""
this=""
state=$(mocp -Q %state 2>/dev/null)
if [ $state == "PLAY" ]; then
	icon=" "
	this=$(mocp -Q %file | sed 's/\//\n/g' | sed '$!d' | sed 's/ /_/g' | awk '$1>0 {print substr($1,1,15)}' | sed 's/_/ /g')
	this=$this"..."
elif [ $state == "PAUSE" ]; then
	icon=" "
	this=$(mocp -Q %file | sed 's/\//\n/g' | sed '$!d' | sed 's/ /_/g' | awk '$1>0 {print substr($1,1,15)}' | sed 's/_/ /g')
	this=$this"..."
else
	icon=" "
	this="[STOP]"
fi



username="p"
password="r0e"
icon2="  "

icon3=" "

#echo $MEMUSED"/"$MEMTOT

oldtime=$(cat /home/phil/slstatus/time)
current=$(date +%s)

passed=$[ current-oldtime ]
icon5="  "
if [ $passed -gt 300 ]
then
weathernow=$(curl wttr.in/Caerphilly?format="%l+%C+%f" 2>/dev/null | cut -d' ' -f2-)
#mailcount=$(curl -u $username:$password  --silent "https://mail.google.com/mail/feed/atom" | grep -oPm1 "(?<=<fullcount>)[^<]+")
actualupdates=$(checkupdates | wc -l)

date +%s > /home/phil/slstatus/time

#echo $mailcount > /home/phil/slstatus/mail
echo $weathernow > /home/phil/slstatus/weather
echo $actualupdates > /home/phil/slstatus/updates
else
weathernow=$(cat /home/phil/slstatus/weather)
#mailcount=$(cat /home/phil/slstatus/mail)
actualupdates=$(cat /home/phil/slstatus/updates)
fi

echo $MEMUSED"/"$MEMTOT"  ^c#99FF99^"$icon5" ^c#FFFF99^"$weathernow"  ^c#CC99FF^"$icon3"^c#FFCCE5^"$actualupdates " ^c#FF007F^"$icon$this



